version: 1.0.0

client:
  organization: org1
  logging:
    level: info
  cryptoconfig:
    path: ${PWD}/fixtures/crypto-config
  credentialStore:
    path: "/tmp/state-store"
    cryptoStore:
      path: /tmp/msp
  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256
  tlsCerts:
    systemCertPool: true
    client:
      key:
        path: ${PWD}/fixtures/crypto-config/peerOrganizations/org1.alanhou.org/users/User1@org1.alanhou.org/tls/client.key
      cert:
        path: ${PWD}/fixtures/crypto-config/peerOrganizations/org1.alanhou.org/users/User1@org1.alanhou.org/tls/client.crt

channels:
  orgchannel:
    peers:
      peer0.org1.alanhou.org:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.org2.alanhou.org:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0

organizations:
  org1:
    mspid: Org1MSP
    cryptoPath: peerOrganizations/org1.alanhou.org/users/{username}@org1.alanhou.org/msp
    peers:
      - peer0.org1.alanhou.org

  org2:
    mspid: Org2MSP
    cryptoPath: peerOrganizations/org2.alanhou.org/users/{username}@org2.alanhou.org/msp
    peers:
      - peer0.org2.alanhou.org

  ordererorg:
    mspID: OrdererMSP
    cryptoPath: ordererOrganizations/alanhou.org/users/{username}@alanhou.org/msp

orderers:
  orderer.alanhou.org:
    url: orderer.alanhou.org:7050
    grpcOptions:
      ssl-target-name-override: orderer.alanhou.org
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${PWD}/fixtures/crypto-config/ordererOrganizations/alanhou.org/tlsca/tlsca.alanhou.org-cert.pem

peers:
  peer0.org1.alanhou.org:
    url: peer0.org1.alanhou.org:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.alanhou.org
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${PWD}/fixtures/crypto-config/peerOrganizations/org1.alanhou.org/tlsca/tlsca.org1.alanhou.org-cert.pem

  peer0.org2.alanhou.org:
    url: peer0.org2.alanhou.org:9051
    grpcOptions:
      ssl-target-name-override: peer0.org2.alanhou.org
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${PWD}/fixtures/crypto-config/peerOrganizations/org2.alanhou.org/tlsca/tlsca.org2.alanhou.org-cert.pem

entityMatchers:
  peer:
    - pattern: (\w+).org1.alanhou.org:(\d+)
      urlSubstitutionExp: ${1}.org1.alanhou.org:${2}
      sslTargetOverrideUrlSubstitutionExp: ${1}.org1.alanhou.org
      mappedHost: peer0.org1.alanhou.org

    - pattern: (\w+).org2.alanhou.org:(\d+)
      urlSubstitutionExp: ${1}.org2.alanhou.org:${2}
      sslTargetOverrideUrlSubstitutionExp: ${1}.org2.alanhou.org
      mappedHost: peer0.org2.alanhou.org
